# Generated by Django 3.1.4 on 2020-12-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cookie',
            name='description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookie',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookie',
            name='thumbnail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClubFundraiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.club')),
                ('cookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.cookie')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='fundraiser',
            field=models.ManyToManyField(through='pages.ClubFundraiser', to='pages.Cookie'),
        ),
    ]
